/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SfIcon: typeof import('@components/icon/index.vue')['default']
    SfInput: typeof import('@components/input/index.vue')['default']
    SfMenu: typeof import('@components/menu/index.vue')['default']
    SfModal: typeof import('@components/modal/index.vue')['default']
    SfSetBox: typeof import('@components/setBox/index.vue')['default']
    SfSetItem: typeof import('@components/setItem/index.vue')['default']
    SfSetTitle: typeof import('@components/setTitle/index.vue')['default']
  }
}
