/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SfApp: typeof import('@components/app/index.vue')['default']
    SfIcon: typeof import('@components/icon/index.vue')['default']
    SfInput: typeof import('@components/input/index.vue')['default']
    SfLogin: typeof import('@components/login/index.vue')['default']
    SfMenu: typeof import('@components/menu/index.vue')['default']
    SfMixImg: typeof import('@components/mixImg/index.vue')['default']
    SfModal: typeof import('@components/modal/index.vue')['default']
    SfSetBox: typeof import('@components/setBox/index.vue')['default']
    SfSetContainer: typeof import('@components/setContainer/index.vue')['default']
    SfSetItem: typeof import('@components/setItem/index.vue')['default']
    SfSetTitle: typeof import('@components/setTitle/index.vue')['default']
    SfTab: typeof import('@components/tab/index.vue')['default']
    SfTheme: typeof import('@components/theme/index.vue')['default']
    SfTooltip: typeof import('@components/tooltip/index.vue')['default']
    SfViewContainer: typeof import('@components/viewContainer/index.vue')['default']
  }
}
